import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#121212",
	},
	header: {
		backgroundColor: "#121212",
		padding: 20,
		paddingTop: 60,
		borderBottomWidth: 1,
		borderBottomColor: "#e0e0e0",
	},
	headerTitle: {
		fontSize: 28,
		fontWeight: "bold",
		color: "#333",
	},
	profileSection: {
		backgroundColor: "#121212",
		alignItems: "center",
		paddingVertical: 30,
		marginBottom: 15,
	},
	avatarContainer: {
		position: "relative",
		marginBottom: 15,
	},
	avatar: {
		width: 120,
		height: 120,
		borderRadius: 60,
		borderWidth: 4,
		borderColor: "#FFA500",
	},
	avatarPlaceholder: {
		width: 120,
		height: 120,
		borderRadius: 60,
		backgroundColor: "#4CAF50",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 4,
		borderColor: "#45a049",
	},
	avatarPlaceholderText: {
		fontSize: 48,
		fontWeight: "bold",
		color: "#fff",
	},
	editBadge: {
		position: "absolute",
		right: 0,
		bottom: 0,
		backgroundColor: "#2196F3",
		width: 36,
		height: 36,
		borderRadius: 18,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 3,
		borderColor: "#fff",
	},
	editBadgeText: {
		fontSize: 16,
		color: "#fff",
	},
	userName: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#333",
		marginBottom: 5,
	},
	userEmail: {
		fontSize: 14,
		color: "#777",
		marginBottom: 10,
	},
	hintText: {
		fontSize: 12,
		color: "#999",
		fontStyle: "italic",
		marginTop: 5,
	},
	statsContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
		paddingHorizontal: 15,
		marginBottom: 15,
	},
	statCard: {
		backgroundColor: "#1E1E1E",
		width: "48%",
		padding: 20,
		borderRadius: 12,
		alignItems: "center",
		marginBottom: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	statValue: {
		fontSize: 28,
		fontWeight: "bold",
		color: "#FFA500",
		marginBottom: 5,
	},
	statLabel: {
		fontSize: 12,
		color: "#ffffffff",
		textAlign: "center",
	},
	infoSection: {
		paddingHorizontal: 15,
		marginBottom: 15,
	},
	infoCard: {
		backgroundColor: "#1E1E1E",
		borderRadius: 12,
		padding: 20,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	infoRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: "#f0f0f0",
	},
	infoLabel: {
		fontSize: 15,
		color: "#ffffffff",
		fontWeight: "500",
	},
	infoValue: {
		fontSize: 15,
		color: "#FFA500",
		fontWeight: "600",
	},
	menuSection: {
		paddingHorizontal: 15,
		marginBottom: 15,
	},
	menuItem: {
		backgroundColor: "#1E1E1E",
		flexDirection: "row",
		alignItems: "center",
		padding: 16,
		borderRadius: 12,
		marginBottom: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	menuIconContainer: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: "#000000ff",
		justifyContent: "center",
		alignItems: "center",
		marginRight: 15,
	},
	menuIcon: {
		fontSize: 20,
	},
	menuTextContainer: {
		flex: 1,
	},
	menuTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#ffffffff",
		marginBottom: 2,
	},
	menuSubtitle: {
		fontSize: 12,
		color: "#777",
	},
	menuArrow: {
		fontSize: 24,
		color: "#ccc",
	},
	logoutSection: {
		paddingHorizontal: 15,
		marginBottom: 30,
	},
	logoutButton: {
		backgroundColor: "#ce711aff",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 16,
		borderRadius: 12,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 4,
	},
	logoutText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "bold",
	},
	footer: {
		alignItems: "center",
		paddingVertical: 20,
	},
	footerText: {
		fontSize: 12,
		color: "#FFA500",
	},
	// Estilos do Modal
	modalContainer: {
		flex: 1,
		justifyContent: "flex-end",
		backgroundColor: "rgba(0, 0, 0, 0.5)",
	},
	modalContent: {
		backgroundColor: "#000000ff",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		maxHeight: "90%",
	},
	modalHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		padding: 20,
		borderBottomWidth: 1,
		borderBottomColor: "#e0e0e0",
	},
	modalTitle: {
		fontSize: 20,
		fontWeight: "bold",
		color: "#FFA500",
	},
	modalClose: {
		fontSize: 28,
		color: "#999",
		fontWeight: "300",
	},
	modalBody: {
		padding: 20,
	},
	inputGroup: {
		marginBottom: 20,
	},
	inputLabel: {
		fontSize: 14,
		fontWeight: "600",
		color: "#FFA500",
		marginBottom: 8,
	},
	input: {
		backgroundColor: "#f5f5f5",
		borderRadius: 10,
		padding: 15,
		fontSize: 16,
		color: "#333",
		borderWidth: 1,
		borderColor: "#e0e0e0",
	},
	optionsContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
	},
	optionButton: {
		backgroundColor: "#f5f5f5",
		paddingVertical: 10,
		paddingHorizontal: 16,
		borderRadius: 20,
		borderWidth: 2,
		borderColor: "#e0e0e0",
		marginRight: 8,
		marginBottom: 8,
	},
	optionButtonActive: {
		backgroundColor: "#f5f2e8ff",
		borderColor: "#91570cff",
	},
	optionText: {
		fontSize: 14,
		color: "#555",
		fontWeight: "500",
	},
	optionTextActive: {
		color: "#6b4205ff",
		fontWeight: "600",
	},
	saveButton: {
		backgroundColor: "#FFA500",
		margin: 20,
		padding: 16,
		borderRadius: 12,
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 4,
	},
	saveButtonText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "bold",
	},
});
